name: commit release

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Go
      uses: actions/setup-go@v4

    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch IP List
      run: |
        bash fetch.sh

    - name: Convert to MaxMind
      run: |
        go run .

    - name: Set environment
      shell: bash
      run: |
        echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        files: |
          Country.mmdb
          chnroutes4
          chnroutes6
          chnroutes4.ipset
          chnroutes6.ipset
          chnroutes4.rsc
          chnroutes6.rsc
          gfwlist.rsc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
