name: cron release

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Go
        uses: actions/setup-go@v4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch IP List
        run: |
          bash fetch.sh

      - name: Convert to MaxMind
        run: |
          go run .

      - name: Set environment
        shell: bash
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Push release
        run: |
          mkdir publish
          cp -f Country.mmdb publish
          cp -f chnroutes4 publish
          cp -f chnroutes6 publish
          cp -f chnroutes4.ipset publish
          cp -f chnroutes6.ipset publish
          cp -f chnroutes4.rsc publish
          cp -f chnroutes6.rsc publish
          cp -f gfwlist publish
          cp -f gfwlist.rsc publish
          cp -f gfwlist.list publish
          cd publish
          git init
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.CRON_RELEASE_WORKFLOW }}@github.com/${{ github.repository }}"
          git push -f -u origin release
